import { useEffect, useState } from "react";
import { useNavigate, useParams } from "react-router-dom";
import { api } from "@/lib/api";
import { useAuth } from "@/hooks/useAuth";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { toast } from "sonner";
import { Plus, Trash2, Save } from "lucide-react";

interface LineItem {
  id?: string;
  item_name: string;
  description: string;
  qty: number;
  unit_price: number;
  discount: number;
  tax_rate: number;
  line_total: number;
  sort_order: number;
}

export default function InvoiceForm() {
  const { id } = useParams();
  const isEdit = !!id && id !== "new";
  const navigate = useNavigate();
  const { user } = useAuth();

  const [customers, setCustomers] = useState<any[]>([]);
  const [categories, setCategories] = useState<any[]>([]);
  const [loading, setLoading] = useState(false);
  const [saving, setSaving] = useState(false);
  const [visibleCols, setVisibleCols] = useState<Record<string, boolean>>({
    item_name: true, description: true, qty: true, unit_price: true, discount: true, tax: true, line_total: true,
  });

  const [invoiceNumber, setInvoiceNumber] = useState("");
  const [customerId, setCustomerId] = useState("");
  const [categoryId, setCategoryId] = useState("");
  const [issueDate, setIssueDate] = useState(new Date().toISOString().split("T")[0]);
  const [dueDate, setDueDate] = useState("");
  const [notes, setNotes] = useState("");
  const [terms, setTerms] = useState("");
  const [items, setItems] = useState<LineItem[]>([
    { item_name: "", description: "", qty: 1, unit_price: 0, discount: 0, tax_rate: 0, line_total: 0, sort_order: 0 },
  ]);

  useEffect(() => {
    loadDropdowns();
    if (isEdit) loadInvoice();
    else generateNumber();
  }, [id]);

  const loadDropdowns = async () => {
    try {
      const [c, cat, tplSetting] = await Promise.all([
        api.getCustomers(),
        api.getCategories(),
        api.getSetting("template_settings").catch(() => null),
      ]);
      setCustomers(c);
      setCategories(cat);
      if (tplSetting?.value) {
        const tpl = tplSetting.value as any;
        if (tpl.columns) setVisibleCols(tpl.columns);
      }
    } catch (error) {
      console.error('Failed to load dropdowns:', error);
    }
  };

  const generateNumber = async () => {
    // Invoice number will be generated by backend
    setInvoiceNumber("");
  };

  const loadInvoice = async () => {
    setLoading(true);
    try {
      const inv = await api.getInvoice(id!);
      setInvoiceNumber(inv.invoice_number);
      setCustomerId(inv.customer_id ?? "");
      setCategoryId(inv.category_id ?? "");
      setIssueDate(inv.issue_date);
      setDueDate(inv.due_date ?? "");
      setNotes(inv.notes ?? "");
      setTerms(inv.terms ?? "");
      if (inv.items && inv.items.length > 0) {
        setItems(inv.items.map((li: any) => ({ ...li, qty: Number(li.qty), unit_price: Number(li.unit_price), discount: Number(li.discount), tax_rate: Number(li.tax_rate), line_total: Number(li.line_total) })));
      }
    } catch (error) {
      console.error('Failed to load invoice:', error);
    } finally {
      setLoading(false);
    }
  };

  const calcLineTotal = (item: LineItem) => {
    const base = item.qty * item.unit_price;
    const afterDiscount = base - item.discount;
    const tax = afterDiscount * (item.tax_rate / 100);
    return Math.max(0, afterDiscount + tax);
  };

  const updateItem = (index: number, field: keyof LineItem, value: any) => {
    const updated = [...items];
    (updated[index] as any)[field] = value;
    // Only auto-calculate if user is NOT directly editing line_total
    if (field !== "line_total") {
      updated[index].line_total = calcLineTotal(updated[index]);
    }
    setItems(updated);
  };

  const addItem = () => {
    setItems([...items, { item_name: "", description: "", qty: 1, unit_price: 0, discount: 0, tax_rate: 0, line_total: 0, sort_order: items.length }]);
  };

  const removeItem = (index: number) => {
    if (items.length <= 1) return;
    setItems(items.filter((_, i) => i !== index));
  };

  const subtotal = items.reduce((s, i) => s + i.qty * i.unit_price, 0);
  const discountTotal = items.reduce((s, i) => s + i.discount, 0);
  const taxTotal = items.reduce((s, i) => s + (i.qty * i.unit_price - i.discount) * (i.tax_rate / 100), 0);
  const grandTotal = items.reduce((s, i) => s + i.line_total, 0);

  const handleSave = async () => {
    if (!invoiceNumber.trim()) { toast.error("Invoice number is required"); return; }
    if (items.some((i) => !i.item_name.trim())) { toast.error("All items need a name"); return; }

    setSaving(true);
    try {
      const invoiceData = {
        customer_id: customerId || null,
        category_id: categoryId || null,
        issue_date: issueDate,
        due_date: dueDate || null,
        notes: notes || null,
        terms: terms || null,
        items: items.map((item, idx) => ({
          item_name: item.item_name,
          description: item.description || null,
          qty: item.qty,
          unit_price: item.unit_price,
          discount: item.discount,
          tax_rate: item.tax_rate,
          sort_order: idx,
        })),
      };

      let invoiceId = id;
      if (isEdit) {
        await api.updateInvoice(id!, invoiceData);
      } else {
        const result = await api.createInvoice(invoiceData);
        invoiceId = result.id;
      }

      toast.success(isEdit ? "Invoice updated" : "Invoice created");
      navigate(`/invoices/${invoiceId}`);
    } catch (err: any) {
      toast.error(err.message || "Failed to save invoice");
    }
    setSaving(false);
  };

  if (loading) return <p className="text-muted-foreground p-6">Loading...</p>;

  return (
    <div className="space-y-6">
      <div className="flex items-center justify-between">
        <h1 className="text-2xl font-bold">{isEdit ? "Edit Invoice" : "New Invoice"}</h1>
        <Button onClick={handleSave} disabled={saving}>
          <Save className="mr-2 h-4 w-4" /> {saving ? "Saving..." : "Save Invoice"}
        </Button>
      </div>

      <div className="grid gap-6 lg:grid-cols-2">
        <Card>
          <CardHeader><CardTitle>Invoice Details</CardTitle></CardHeader>
          <CardContent className="space-y-4">
            <div className="space-y-2">
              <Label>Invoice Number</Label>
              <Input value={invoiceNumber} onChange={(e) => setInvoiceNumber(e.target.value)} />
            </div>
            <div className="space-y-2">
              <Label>Customer</Label>
              <Select value={customerId} onValueChange={setCustomerId}>
                <SelectTrigger><SelectValue placeholder="Select customer" /></SelectTrigger>
                <SelectContent>
                  {customers.map((c) => (
                    <SelectItem key={c.id} value={c.id}>{c.name}</SelectItem>
                  ))}
                </SelectContent>
              </Select>
            </div>
            <div className="space-y-2">
              <Label>Category</Label>
              <Select value={categoryId} onValueChange={setCategoryId}>
                <SelectTrigger><SelectValue placeholder="Select category" /></SelectTrigger>
                <SelectContent>
                  {categories.map((c) => (
                    <SelectItem key={c.id} value={c.id}>{c.name}</SelectItem>
                  ))}
                </SelectContent>
              </Select>
            </div>
            <div className="grid grid-cols-2 gap-4">
              <div className="space-y-2">
                <Label>Issue Date</Label>
                <Input type="date" value={issueDate} onChange={(e) => setIssueDate(e.target.value)} />
              </div>
              <div className="space-y-2">
                <Label>Due Date</Label>
                <Input type="date" value={dueDate} onChange={(e) => setDueDate(e.target.value)} />
              </div>
            </div>
          </CardContent>
        </Card>

      </div>

      <Card>
        <CardHeader>
          <div className="flex items-center justify-between">
            <CardTitle>Line Items</CardTitle>
            <Button variant="outline" size="sm" onClick={addItem}>
              <Plus className="mr-1 h-4 w-4" /> Add Item
            </Button>
          </div>
        </CardHeader>
        <CardContent>
          <div className="space-y-3">
            {items.map((item, idx) => (
              <div key={idx} className="grid gap-2 items-end rounded-lg border p-3" style={{ gridTemplateColumns: "1fr" }}>
                <div className="grid grid-cols-12 gap-2 items-end">
                  {visibleCols.item_name !== false && (
                    <div className="col-span-12 sm:col-span-3 space-y-1">
                      <Label className="text-xs">Item Name</Label>
                      <Input value={item.item_name} onChange={(e) => updateItem(idx, "item_name", e.target.value)} placeholder="Item name" />
                    </div>
                  )}
                  {visibleCols.description !== false && (
                    <div className="col-span-12 sm:col-span-2 space-y-1">
                      <Label className="text-xs">Description</Label>
                      <Input value={item.description} onChange={(e) => updateItem(idx, "description", e.target.value)} placeholder="Description" />
                    </div>
                  )}
                  {visibleCols.qty !== false && (
                    <div className="col-span-4 sm:col-span-1 space-y-1">
                      <Label className="text-xs">Qty</Label>
                      <Input type="number" min={0} value={item.qty} onChange={(e) => updateItem(idx, "qty", Number(e.target.value))} />
                    </div>
                  )}
                  {visibleCols.unit_price !== false && (
                    <div className="col-span-4 sm:col-span-2 space-y-1">
                      <Label className="text-xs">Unit Price</Label>
                      <Input type="number" min={0} value={item.unit_price} onChange={(e) => updateItem(idx, "unit_price", Number(e.target.value))} />
                    </div>
                  )}
                  {visibleCols.discount !== false && (
                    <div className="col-span-4 sm:col-span-1 space-y-1">
                      <Label className="text-xs">Discount</Label>
                      <Input type="number" min={0} value={item.discount} onChange={(e) => updateItem(idx, "discount", Number(e.target.value))} />
                    </div>
                  )}
                  {visibleCols.tax !== false && (
                    <div className="col-span-4 sm:col-span-1 space-y-1">
                      <Label className="text-xs">Tax %</Label>
                      <Input type="number" min={0} value={item.tax_rate} onChange={(e) => updateItem(idx, "tax_rate", Number(e.target.value))} />
                    </div>
                  )}
                  {visibleCols.line_total !== false && (
                    <div className="col-span-6 sm:col-span-1 space-y-1">
                      <Label className="text-xs">Total</Label>
                      <Input type="number" min={0} value={item.line_total} onChange={(e) => updateItem(idx, "line_total", Number(e.target.value))} />
                    </div>
                  )}
                  <div className="col-span-2 sm:col-span-1 flex justify-end">
                    <Button variant="ghost" size="icon" onClick={() => removeItem(idx)} disabled={items.length <= 1}>
                      <Trash2 className="h-4 w-4 text-destructive" />
                    </Button>
                  </div>
                </div>
              </div>
            ))}
          </div>

          <div className="mt-6 flex justify-end">
            <div className="w-64 space-y-2 text-sm">
              <div className="flex justify-between"><span className="text-muted-foreground">Subtotal</span><span>Rs. {subtotal.toLocaleString()}</span></div>
              <div className="flex justify-between"><span className="text-muted-foreground">Discount</span><span>-Rs. {discountTotal.toLocaleString()}</span></div>
              <div className="flex justify-between"><span className="text-muted-foreground">Tax</span><span>Rs. {taxTotal.toLocaleString()}</span></div>
              <div className="flex justify-between border-t pt-2 font-bold text-base"><span>Grand Total</span><span>Rs. {grandTotal.toLocaleString()}</span></div>
            </div>
          </div>
        </CardContent>
      </Card>
    </div>
  );
}
